[web]
3.107.112.144 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
3.104.117.153 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
3.26.241.22 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
13.238.255.32 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3